version: '3.8'

services:
  central-unit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: central-unit
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - ALG_RUNNER_URL=http://alg-runner:8000
    networks:
      - tp-net
    volumes:
      - ./data:/app/data

networks:
  tp-net:
    external: true